### ISSUE TITLE
Open SGF in GoKibitz

### ISSUE THREAD

**Issue by jkk** [jkk/shinkgs#113]
Must be logged into GoKibitz:

POST https://gokibitz.com/api/kifu/upload
Content-Type: application/json;charset=UTF-8
`{url: "http://files.gokgs.com/games/2017/4/1/Dom-Amore.sgf", public: false}`

Response:

`{message: "Kifu successfully created!", _id: "590e33e6336a7c352194c36d", shortid: "rkkgV3sy-"}`

https://gokibitz.com/kifu/rkkgV3sy-

**Comment by jkk** [comment]
@neagle what's the best way to accomplish this? Is there a URL I could construct and open to prompt the user to login/upload? Not sure that the POST method described above would actually work.

I just added a similar feature for EidoGo which opens a URL such as "http://eidogo.com/#url:http://files.gokgs.com/games/2017/4/1/Dom-Amore.sgf". But EidoGo is a bit more lax about opening random URLs.

**Comment by neagle** [comment]
I don't have any objection to opening random URLs. The only issue is creating a workflow to have allow users to log in / register on GoKibitz if they haven't already, which is doable, but needs doing. This is work I'm happy to do on the GoKibitz end, especially because I (and the rest of the world) am excited about ShinKGS, but I'm afraid I can't promise it this week. I'll try for next week and will post updated details about the URL to use. And, yeah, I'd probably be happy to do the implementation on this end, too.

**Comment by jkk** [comment]
@neagle no rush at all! Totally up to you. Just wanted to have someplace to track this. I tend to make issues for every harebrained idea that pops into my head 🙂

**Comment by neagle** [comment]
We can now use the URL pattern https://gokibitz.com/fetch#http://someurl/somegame.sgf to bring up a custom screen for uploading the SGF that will prompt users to log in / sign up if they're not currently logged in.

![image](https://cloud.githubusercontent.com/assets/176993/26111937/82e9f466-3a24-11e7-9910-d8571749890e.png)

It requires another step (users have to click the fetch button), but I think it's important to let users choose whether to make the SGF public or private in the GoKibitz context.

Next I'll work on adding the "Open in GoKibitz" link after the "Open in EidoGo" link already present.

**Comment by jkk** [comment]
Sweet! I'm nearing the end of a crunch at work and can't wait to jump back into Shin and get PRs reviewed

**Comment by neagle** [comment]
It's rough when you've got a lot of work and a personal project you're really excited about. 😁 Good luck!
