### ISSUE TITLE
Upgrade create-react-app to latest

### ISSUE THREAD

**Issue by jkk** [jkk/shinkgs#131]
https://github.com/facebookincubator/create-react-app/issues/2172

**Comment by beejunk** [comment]
I might tackle this one next. I ran into an issue creating a *now* deployment because one of the source maps was bigger than 1 MB, which is too much for the free version of *now*. This can be fixed by disabling source maps for the build, but that feature is only available on newer versions of create-react-app.

**Comment by hadim** [comment]
`react-scripts` has been updated to `2.0.0-next.a671462c` due to a compatibility bug in the >< 2 version. We should definitively update to a stable 2 version when it gets released.
