### ISSUE TITLE
Rank graph

### ISSUE THREAD

**Issue by jkk** [jkk/shinkgs#23]
New tab in details modal.

Can we use the image from here?

http://www.gokgs.com/graphPage.jsp?user=wrap

**Comment by ohyou** [comment]
Seems like all the links follow this pattern:

http://www.gokgs.com/servlet/graph/<nickname>-<graph_locale>.png

E.g.  
http://www.gokgs.com/servlet/graph/wrap-en_US.png  
http://www.gokgs.com/servlet/graph/ohyou-es_ES.png  
http://www.gokgs.com/servlet/graph/twoeye-ru_RU.png

Probably need to just load them and insert into the DOM. Not sure about using the direct link because of possible CORS and protocol (http/https) issues.

**Comment by neagle** [comment]
Seems like it would be more fun to just create our own graph, since the API Docs [claim we can get the rank graph data](https://www.gokgs.com/json/downstream.html#DETAILS_RANK_GRAPH). I was able to get the project bootstrapped yesterday afternoon and will take a look at this ticket this weekend as a way to get my feet wet.

**Comment by jkk** [comment]
@neagle That sounds great. I was just looking for something fast and easy to start but a proper graph is definitely better. Only thing I ask is that if you use a third-party graph lib, pull in the dependency lazily with `require.ensure` - I'd like to keep bundles relatively small.

**Comment by neagle** [comment]
Yeah, I was thinking of using [Chartist.js](https://github.com/fraserxu/react-chartist). Thanks for the tip about `require.ensure`: I'll be sure to use that.

**Comment by neagle** [comment]
And fast and easy makes a ton of sense from the perspective of the whole project. Since I'm a random third party, though, I thought I might give myself the luxury of spending disproportionate time on a feature that I would happen to value personally. ;)

**Comment by jkk** [comment]
@neagle exactly! Everyone gets to work on their pet feature. Open source at work 😃

**Comment by neagle** [comment]
Made good progress on this Friday night. Learning how to interact with the KGS API took a while, but it's a good education. I'm currently trying to make `react-chartist` play with `require.ensure`.

**Comment by jkk** [comment]
App.js contains an example of using require.ensure, if it helps:

https://github.com/jkk/shinkgs/blob/master/src/App.js#L118
